# Generated by Django 2.1.7 on 2019-03-15 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190315_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(0, 'woman'), (1, 'man')], null=True),
        ),
    ]
