# Generated by Django 2.1.7 on 2019-03-09 16:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bills', '0003_bill_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
