# Generated by Django 2.1.7 on 2019-03-15 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0004_bill_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='type',
            field=models.IntegerField(choices=[(0, 'expense'), (1, 'income')]),
        ),
    ]
